version: '2'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
#    command: mongod --bind_ip 127.0.0.1

  flask-service:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    restart: always
    container_name: flask
    depends_on:
      - mongodb
    ports:
      - 5000:5000
    environment:
      - "APP_DEBUG=False"
      - "APP_PORT=5000"
      - "MONGO_HOSTNAME=mongodb"

volumes:
  mongodb_data:
    driver: local